version: 1
disable_existing_loggers: False

formatters:
  basic:
    format: '[{asctime}] [{levelname:<8}] {name}: {message}'
    datefmt: '%Y-%m-%d %H:%M:%S'
    style: '{'

handlers:
  console:
    class: logging.StreamHandler
    formatter: basic
    stream: ext://sys.stdout

  rotating_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: basic
    filename: logs/app.log
    when: midnight
    interval: 1
    backupCount: 7
    encoding: utf-8

  error_file:
    class: logging.FileHandler
    formatter: basic
    filename: logs/error.log
    level: ERROR
    encoding: utf-8

loggers:
  app:
    level: DEBUG
    handlers: [console, rotating_file, error_file]
    propagate: False

  app.errors:
    level: DEBUG
    handlers: [console, rotating_file, error_file]
    propagate: False

  app.admin:
    level: DEBUG
    handlers: [console, rotating_file, error_file]
    propagate: False

  app.participant:
    level: DEBUG
    handlers: [console, rotating_file, error_file]
    propagate: False

  app.auth:
    level: DEBUG
    handlers: [console, rotating_file, error_file]
    propagate: False

  app.decorators:
    level: DEBUG
    handlers: [console, rotating_file, error_file]
    propagate: False

root:
  level: DEBUG
  handlers: [console, rotating_file, error_file]
